export {
  documentSchema,
  editorConfigSchema,
  secretsSchema,
  vaultSchema,
  type CreateDocumentInput,
  type CreateVaultInput,
  type Document,
  type EditorConfig,
  type MoveDocumentInput,
  type RenameDocumentInput,
  type RenameVaultInput,
  type Secrets,
  type UpdateContentInput,
  type Vault,
} from './api'
