// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package users

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
